### ISSUE TITLE
When to use random_sized_crop

### ISSUE THREAD

**Issue by macaodha** [philiptheother/FeatureDecoupling#1]
Hi there, 

Looking through the code it seems like `transforms.RandomResizedCrop` is used when training with [self-supervision](https://github.com/philiptheother/FeatureDecoupling/blob/master/pytorch_feature_decoupling/config/ImageNet_Decoupling_AlexNet.py#L8) but  then it is disabled when training the [linear classifier](https://github.com/philiptheother/FeatureDecoupling/blob/master/pytorch_feature_decoupling/config/ImageNet_LinearClassifiers_ImageNet_Decoupling_AlexNet_Features.py#L8). I was just wondering if there was a reason for the change, and if it makes a big difference in the final performance? 

Thanks!

**Comment by philiptheother** [comment]
Hi Oisin,

Thanks for your question. This data augmentation is chosen according to the setting in [RotNet](https://github.com/gidariss/FeatureLearningRotNet/blob/master/config/ImageNet_LinearClassifiers_ImageNet_RotNet_AlexNet_Features.py) in order to make a fair comparison. I didn't test other data augmentation strategies for linear evaluation.

**Comment by macaodha** [comment]
Makes sense. Thanks for the reply.

**Comment by Chen-Song** [comment]
Hi @macaodha , have you found the prob.dat file?
Thanks.
