### ISSUE TITLE
Any results on smaller datasets

### ISSUE THREAD

**Issue by PaulAlbert31** [philiptheother/FeatureDecoupling#3]
Hi,
Thanks for your work and for sharing the code, the results are very good on ImageNet and other big image datasets.
I was wondering if you ran experiments on smaller images such as the ones in the CIFARs. I tried runing them myself but I am not so sure about how to configure the NCE layer and the results I get are really poor.

Do you have any observations to share over this ?

Thanks

**Comment by philiptheother** [comment]
Hi,
I didn't run any expriments on CIFAR datasets, but you could try some hyperparameters suggested in the Non-Parametric Instance Discrimination paper. They have reported the results on CIFAR10 in their article. Even with different networks the features from the last layer are always used for rotation prediction task and rotation invariance task. According to my understanding, on CIFAR10 it is also possible to directly optimize the non-parametic objective instead of approximating it with NCE.

**Comment by PaulAlbert31** [comment]
Thanks for the reply ! I'll have a look
